name: 'Find PR'
description: 'Finds an open pull request for the current branch'

inputs:
  github-token:
    description: 'GitHub token for API calls'
    required: true

outputs:
  pr_found:
    description: 'Whether a PR was found (true/false)'
    value: ${{ steps.set-outputs.outputs.pr_found }}
  sha:
    description: 'The commit SHA of the PR head'
    value: ${{ steps.set-outputs.outputs.sha }}
  pr_number:
    description: 'The PR number (if found)'
    value: ${{ steps.set-outputs.outputs.pr_number }}

runs:
  using: 'composite'
  steps:
    - name: Find open PR for branch
      id: find-pr
      uses: actions/github-script@v8
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const ref = github.ref || context.ref;
          const branch = ref.replace('refs/heads/', '');
          const response = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: `${context.repo.owner}:${branch}`,
            state: 'open',
            'per_page': 1
          });
          
          const prs = response.data;
          
          if (prs && prs.length > 0) {
            const sha = prs[0].head.sha;
            const prNumber = prs[0].number;
            return {
              pr_found: 'true',
              sha: sha,
              pr_number: prNumber.toString()
            };
          } else {
            return {
              pr_found: 'false',
              sha: '',
              pr_number: ''
            };
          }
    - name: Set outputs
      shell: bash
      id: set-outputs
      run: |
        RESULT='${{ steps.find-pr.outputs.result }}'
        # Parse JSON result and set outputs
        PR_FOUND=$(echo "$RESULT" | jq -r '.pr_found // "false"')
        SHA=$(echo "$RESULT" | jq -r '.sha // ""')
        PR_NUMBER=$(echo "$RESULT" | jq -r '.pr_number // ""')
        {
          echo "pr_found=$PR_FOUND"
          echo "sha=$SHA"
          echo "pr_number=$PR_NUMBER"
        } >> $GITHUB_OUTPUT
