# Generated by Django 6.0 on 2025-12-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsconfig',
            name='display_name',
            field=models.CharField(help_text='Human-readable display name for the news configuration', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsconfig',
            name='key',
            field=models.SlugField(help_text='The name of the news config.yaml (i.e. the name field in the yaml-file)', max_length=100),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='When the log entry was created')),
                ('level', models.CharField(help_text='Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)', max_length=20)),
                ('logger_name', models.CharField(help_text='Name of the logger that created this entry', max_length=255)),
                ('message', models.TextField(help_text='The log message')),
                ('config_name', models.CharField(blank=True, help_text='News config name extracted from the log message', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was inserted into the database')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='newsserver__created_abb4f6_idx'), models.Index(fields=['level'], name='newsserver__level_9eeb87_idx'), models.Index(fields=['config_name'], name='newsserver__config__9ab992_idx')],
            },
        ),
    ]
