# Generated by Django 6.0 on 2025-12-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0002_alter_newsconfig_display_name_alter_newsconfig_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='config_name',
            field=models.CharField(blank=True, default='', help_text='News config name extracted from the log message', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsconfig',
            name='key',
            field=models.SlugField(help_text='The name of the news config.yaml (i.e. the name field in the yaml-file)', max_length=100, unique=True),
        ),
    ]
