# Generated by Django 6.0 on 2025-12-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0003_alter_logentry_config_name_alter_newsconfig_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('articles_analyzed', models.IntegerField(default=0, help_text='Number of articles analyzed')),
                ('stories_identified', models.IntegerField(default=0, help_text='Number of stories identified')),
                ('top_stories', models.TextField(blank=True, help_text='JSON or text summary of top stories')),
                ('error_count', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True, help_text='List of errors')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_summaries', to='newsserver.newsconfig')),
            ],
            options={
                'verbose_name_plural': 'Analysis summaries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('articles_scraped', models.IntegerField(default=0, help_text='Number of articles scraped')),
                ('articles_saved', models.IntegerField(default=0, help_text='Number of articles saved to DB')),
                ('error_count', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True, help_text='List of errors')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrape_summaries', to='newsserver.newsconfig')),
            ],
            options={
                'verbose_name_plural': 'Scrape summaries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
