# Generated by Django on 2025-12-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0004_analysissummary_scrapesummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
