# Generated by Django 6.0 on 2026-01-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0005_remove_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_file', models.CharField(db_index=True, help_text='Configuration file name (config key)', max_length=100)),
                ('title', models.CharField(help_text='Article title', max_length=500)),
                ('content', models.TextField(blank=True, help_text='Full article content')),
                ('summary', models.TextField(blank=True, help_text='Generated article summary')),
                ('source', models.CharField(help_text='News source name', max_length=100)),
                ('url', models.CharField(db_index=True, help_text='Article URL', max_length=1000, unique=True)),
                ('published_date', models.DateTimeField(blank=True, help_text='Original publication date', null=True)),
                ('scraped_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date when article was scraped')),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment analysis score (compound score)', null=True)),
                ('sentiment_label', models.CharField(blank=True, help_text='Sentiment label (positive, negative, neutral)', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Articles',
                'ordering': ['-scraped_date'],
                'indexes': [models.Index(fields=['config_file', 'scraped_date'], name='newsserver__config__65c3c0_idx')],
            },
        ),
    ]
