# Generated by Django 6.0 on 2026-01-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0006_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(db_index=True, help_text='Article URL', max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('url', 'config_file'), name='unique_url_per_config'),
        ),
    ]
