# Generated by Django 6.0 on 2026-01-16 17:09

from django.db import migrations


def create_subscriber_configs_table_forward(apps, schema_editor):
    """Create the join table if it doesn't exist."""
    db_vendor = schema_editor.connection.vendor
    table_name = "newsserver_subscriber_configs"
    
    with schema_editor.connection.cursor() as cursor:
        # Check if table exists
        if db_vendor == "postgresql":
            cursor.execute(
                """
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                );
                """,
                [table_name],
            )
            exists = cursor.fetchone()[0]
            
            if not exists:
                cursor.execute(
                    """
                    CREATE TABLE "newsserver_subscriber_configs" (
                        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        "subscriber_id" bigint NOT NULL,
                        "newsconfig_id" bigint NOT NULL,
                        CONSTRAINT "newsserver_subscriber_co_subscriber_id_newsconfig_b14b25d2_uniq" 
                            UNIQUE ("subscriber_id", "newsconfig_id"),
                        CONSTRAINT "newsserver_subscribe_subscriber_id_8929bbff_fk_newsserve" 
                            FOREIGN KEY ("subscriber_id") REFERENCES "newsserver_subscriber" ("id") 
                            DEFERRABLE INITIALLY DEFERRED,
                        CONSTRAINT "newsserver_subscribe_newsconfig_id_78a3ceff_fk_newsserve" 
                            FOREIGN KEY ("newsconfig_id") REFERENCES "newsserver_newsconfig" ("id") 
                            DEFERRABLE INITIALLY DEFERRED
                    );
                    """
                )
                cursor.execute(
                    """
                    CREATE INDEX "newsserver_subscriber_configs_subscriber_id_8929bbff" 
                    ON "newsserver_subscriber_configs" ("subscriber_id");
                    """
                )
                cursor.execute(
                    """
                    CREATE INDEX "newsserver_subscriber_configs_newsconfig_id_78a3ceff" 
                    ON "newsserver_subscriber_configs" ("newsconfig_id");
                    """
                )
        else:  # sqlite
            cursor.execute(
                """
                SELECT name FROM sqlite_master 
                WHERE type='table' AND name=?;
                """,
                [table_name],
            )
            exists = cursor.fetchone() is not None
            
            if not exists:
                cursor.execute(
                    """
                    CREATE TABLE "newsserver_subscriber_configs" (
                        "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                        "subscriber_id" bigint NOT NULL,
                        "newsconfig_id" bigint NOT NULL,
                        FOREIGN KEY ("subscriber_id") REFERENCES "newsserver_subscriber" ("id") 
                            DEFERRABLE INITIALLY DEFERRED,
                        FOREIGN KEY ("newsconfig_id") REFERENCES "newsserver_newsconfig" ("id") 
                            DEFERRABLE INITIALLY DEFERRED
                    );
                    """
                )
                cursor.execute(
                    """
                    CREATE UNIQUE INDEX "newsserver_subscriber_co_subscriber_id_newsconfig_b14b25d2_uniq" 
                    ON "newsserver_subscriber_configs" ("subscriber_id", "newsconfig_id");
                    """
                )
                cursor.execute(
                    """
                    CREATE INDEX "newsserver_subscriber_configs_subscriber_id_8929bbff" 
                    ON "newsserver_subscriber_configs" ("subscriber_id");
                    """
                )
                cursor.execute(
                    """
                    CREATE INDEX "newsserver_subscriber_configs_newsconfig_id_78a3ceff" 
                    ON "newsserver_subscriber_configs" ("newsconfig_id");
                    """
                )


def create_subscriber_configs_table_reverse(apps, schema_editor):
    """Reverse migration - drop the table if it exists."""
    # No-op - we don't want to drop the table on reverse
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0007_alter_article_url_article_unique_url_per_config'),
    ]

    operations = [
        migrations.RunPython(
            create_subscriber_configs_table_forward,
            create_subscriber_configs_table_reverse,
        ),
    ]
