# Generated by Django 6.0 on 2026-01-16 17:09

from django.db import migrations


def rename_column_forward(apps, schema_editor):
    """Rename newsconfiguration_id to newsconfig_id."""
    db_vendor = schema_editor.connection.vendor
    table_name = "newsserver_subscriber_configs"
    old_column = "newsconfiguration_id"
    new_column = "newsconfig_id"
    
    with schema_editor.connection.cursor() as cursor:
        # Check if old column exists
        if db_vendor == "postgresql":
            cursor.execute(
                """
                SELECT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = %s 
                    AND column_name = %s
                );
                """,
                [table_name, old_column],
            )
            old_exists = cursor.fetchone()[0]
            
            cursor.execute(
                """
                SELECT EXISTS (
                    SELECT FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = %s 
                    AND column_name = %s
                );
                """,
                [table_name, new_column],
            )
            new_exists = cursor.fetchone()[0]
            
            if old_exists and not new_exists:
                # Drop the old foreign key constraint first
                cursor.execute(
                    """
                    SELECT constraint_name 
                    FROM information_schema.table_constraints 
                    WHERE table_schema = 'public' 
                    AND table_name = %s 
                    AND constraint_type = 'FOREIGN KEY'
                    AND constraint_name LIKE %s;
                    """,
                    [table_name, f'%{old_column}%'],
                )
                fk_constraints = cursor.fetchall()
                for (constraint_name,) in fk_constraints:
                    cursor.execute(
                        f'ALTER TABLE "{table_name}" DROP CONSTRAINT IF EXISTS "{constraint_name}";'
                    )
                
                # Drop the old index
                cursor.execute(
                    """
                    SELECT indexname 
                    FROM pg_indexes 
                    WHERE tablename = %s 
                    AND indexname LIKE %s;
                    """,
                    [table_name, f'%{old_column}%'],
                )
                indexes = cursor.fetchall()
                for (index_name,) in indexes:
                    cursor.execute(f'DROP INDEX IF EXISTS "{index_name}";')
                
                # Rename the column
                cursor.execute(
                    f'ALTER TABLE "{table_name}" RENAME COLUMN "{old_column}" TO "{new_column}";'
                )
                
                # Recreate the foreign key constraint
                cursor.execute(
                    """
                    ALTER TABLE "newsserver_subscriber_configs" 
                    ADD CONSTRAINT "newsserver_subscribe_newsconfig_id_78a3ceff_fk_newsserve" 
                    FOREIGN KEY ("newsconfig_id") REFERENCES "newsserver_newsconfig" ("id") 
                    DEFERRABLE INITIALLY DEFERRED;
                    """
                )
                
                # Recreate the index
                cursor.execute(
                    """
                    CREATE INDEX IF NOT EXISTS "newsserver_subscriber_configs_newsconfig_id_78a3ceff" 
                    ON "newsserver_subscriber_configs" ("newsconfig_id");
                    """
                )
                
                # Update the unique constraint if it references the old column
                cursor.execute(
                    """
                    ALTER TABLE "newsserver_subscriber_configs" 
                    DROP CONSTRAINT IF EXISTS "newsserver_subscriber_co_subscriber_id_newsconfig_b14b25d2_uniq";
                    """
                )
                cursor.execute(
                    """
                    ALTER TABLE "newsserver_subscriber_configs" 
                    ADD CONSTRAINT "newsserver_subscriber_co_subscriber_id_newsconfig_b14b25d2_uniq" 
                    UNIQUE ("subscriber_id", "newsconfig_id");
                    """
                )
        else:  # sqlite
            # SQLite doesn't support ALTER TABLE RENAME COLUMN in older versions
            # We need to recreate the table
            cursor.execute(
                """
                SELECT name FROM sqlite_master 
                WHERE type='table' AND name=?;
                """,
                [table_name],
            )
            if cursor.fetchone():
                # Check if old column exists
                cursor.execute(f'PRAGMA table_info({table_name})')
                columns = {row[1]: row[0] for row in cursor.fetchall()}
                
                if old_column in columns and new_column not in columns:
                    # SQLite 3.25.0+ supports ALTER TABLE RENAME COLUMN
                    try:
                        cursor.execute(
                            f'ALTER TABLE "{table_name}" RENAME COLUMN "{old_column}" TO "{new_column}";'
                        )
                    except Exception:
                        # Fallback: recreate table (for older SQLite)
                        # This is more complex and would require preserving data
                        # For now, just raise an error suggesting SQLite upgrade
                        raise RuntimeError(
                            "SQLite version 3.25.0+ required for column rename. "
                            "Please upgrade SQLite or manually rename the column."
                        )


def rename_column_reverse(apps, schema_editor):
    """Reverse: rename newsconfig_id back to newsconfiguration_id."""
    # This is a no-op for safety - we don't want to break things
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0008_create_subscriber_configs_table'),
    ]

    operations = [
        migrations.RunPython(
            rename_column_forward,
            rename_column_reverse,
        ),
    ]
