# Generated by Django 6.0 on 2026-01-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0010_fix_foreign_key_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Source name (e.g., 'Example News Source')", max_length=200)),
                ('url', models.URLField(help_text='Source URL', max_length=500, unique=True)),
                ('type', models.CharField(choices=[('rss', 'RSS')], default='rss', help_text='Source type', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News sources',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='newsconfig',
            name='key',
            field=models.SlugField(help_text="A unique identifier for the news configuration (e.g., 'technology', 'world')", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='news_sources',
            field=models.ManyToManyField(blank=True, help_text='News sources for this configuration', related_name='configs', to='newsserver.newssource'),
        ),
    ]
