# Generated by Django 6.0 on 2026-01-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0011_newssource_alter_newsconfig_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsconfig',
            name='country',
            field=models.CharField(default='US', help_text='Country code', max_length=10),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='database_url',
            field=models.CharField(default='${DATABASE_URL}', help_text='Database URL (supports environment variable expansion)', max_length=500),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text='Whether email is enabled'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable/disable this configuration'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='language',
            field=models.CharField(default='en', help_text='Language code', max_length=10),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='llm_base_url',
            field=models.CharField(blank=True, default='http://localhost:11434', help_text='Base URL for the LLM service (unused if not ollama)', max_length=500),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='llm_judge_enabled',
            field=models.BooleanField(default=False, help_text='Whether to enable LLM-as-a-judge validation'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='llm_judge_max_retries',
            field=models.IntegerField(default=2, help_text='Maximum retry attempts when judge detects violations'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='llm_judge_model',
            field=models.CharField(default='', help_text='Model identifier for the judge LLM', max_length=200),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='llm_max_tokens',
            field=models.IntegerField(default=16384, help_text='Maximum tokens to generate'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='llm_model',
            field=models.CharField(default='', help_text='LLM model identifier', max_length=200),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='llm_name_validation_enabled',
            field=models.BooleanField(default=False, help_text='Whether to validate named entities against source content'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='llm_name_validation_max_retries',
            field=models.IntegerField(default=2, help_text='Maximum rewrite attempts when unverified entities are found'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='llm_provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('gemini', 'Gemini')], default='ollama', help_text='LLM provider name', max_length=50),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='llm_spacy_model',
            field=models.CharField(default='en_core_web_sm', help_text='spaCy model for named entity recognition', max_length=200),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='llm_temperature',
            field=models.FloatField(default=0.0, help_text='Sampling temperature (0-1)'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='logging_format',
            field=models.CharField(default='%(asctime)s [%(levelname)s - %(name)s] %(message)s', help_text='Log format string', max_length=500),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='logging_level',
            field=models.CharField(default='INFO', help_text='Logging level', max_length=20),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='report_format',
            field=models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown'), ('text', 'Text')], default='html', help_text='Report format', max_length=20),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='report_include_sentiment_charts',
            field=models.BooleanField(default=True, help_text='Whether to include sentiment charts'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='report_include_summaries',
            field=models.BooleanField(default=True, help_text='Whether to include article summaries'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='report_lookback_days',
            field=models.IntegerField(default=7, help_text='Number of days to look back for articles'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='report_max_articles_per_source',
            field=models.IntegerField(default=10, help_text='Maximum articles per source in report'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='scheduler_daily_scrape_enabled',
            field=models.BooleanField(default=True, help_text='Whether daily scrape is enabled'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='scheduler_daily_scrape_hour',
            field=models.IntegerField(default=2, help_text='Hour for daily scrape (0-23)'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='scheduler_daily_scrape_minute',
            field=models.IntegerField(default=0, help_text='Minute for daily scrape (0-59)'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='scheduler_timezone',
            field=models.CharField(default='UTC', help_text='Timezone for scheduler', max_length=50),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='scheduler_weekly_analysis_day_of_week',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', help_text='Day of week for weekly analysis', max_length=10),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='scheduler_weekly_analysis_enabled',
            field=models.BooleanField(default=True, help_text='Whether weekly analysis is enabled'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='scheduler_weekly_analysis_hour',
            field=models.IntegerField(default=9, help_text='Hour for weekly analysis (0-23)'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='scheduler_weekly_analysis_lookback_days',
            field=models.IntegerField(default=7, help_text='Number of days to look back for weekly analysis'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='scheduler_weekly_analysis_minute',
            field=models.IntegerField(default=0, help_text='Minute for weekly analysis (0-59)'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='sentiment_comparison_threshold',
            field=models.FloatField(default=0.3, help_text='Threshold for comparing sentiments'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='sentiment_method',
            field=models.CharField(choices=[('vader', 'VADER'), ('textblob', 'TextBlob'), ('pysentimiento', 'PySentimiento'), ('hybrid', 'Hybrid (VADER + TextBlob)')], default='pysentimiento', help_text='Sentiment analysis method', max_length=50),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='story_clustering_algorithm',
            field=models.CharField(choices=[('dbscan', 'DBSCAN'), ('greedy', 'Greedy')], default='dbscan', help_text='Clustering algorithm to use', max_length=50),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='story_clustering_dbscan_min_samples',
            field=models.IntegerField(default=2, help_text='Minimum number of neighbors to be a core point'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='story_clustering_embedding_model',
            field=models.CharField(default='Xenova/all-mpnet-base-v2', help_text='Model for embeddings', max_length=200),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='story_clustering_min_sources',
            field=models.IntegerField(default=2, help_text='Minimum sources for a story'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='story_clustering_sampling_central_count',
            field=models.IntegerField(default=4, help_text='Number of central articles to select'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='story_clustering_sampling_diverse_count',
            field=models.IntegerField(default=4, help_text='Number of diverse articles via MMR'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='story_clustering_sampling_recent_count',
            field=models.IntegerField(default=6, help_text='Number of recent articles to select'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='story_clustering_sampling_similarity_floor',
            field=models.FloatField(default=0.4, help_text='Minimum centroid similarity for MMR'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='story_clustering_similarity_threshold',
            field=models.FloatField(default=0.7, help_text='Threshold for similarity'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='story_clustering_top_stories_count',
            field=models.IntegerField(default=5, help_text='Number of top stories to identify'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='summarization_article_order',
            field=models.CharField(choices=[('chronological', 'Chronological')], default='chronological', help_text='Order for processing articles', max_length=50),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='summarization_max_articles_batch',
            field=models.IntegerField(default=1, help_text='Maximum articles per batch'),
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='summarization_two_pass_enabled',
            field=models.BooleanField(default=True, help_text='Whether to use two-pass summarization'),
        ),
    ]
