# Generated by Django 6.0 on 2026-01-17
"""Add ForeignKey from Article to NewsConfig.

This migration:
1. Adds a nullable `config` ForeignKey to Article
2. Makes `config_file` nullable (for backward compatibility)
3. Removes the old index on config_file + scraped_date
4. Removes the old unique constraint on url + config_file
5. Adds new index on config + scraped_date
6. Adds new unique constraint on url + config
7. Migrates existing data from config_file to config FK
"""

from django.db import migrations, models
import django.db.models.deletion


def migrate_config_file_to_config_fk(apps, schema_editor):
    """Migrate existing Article.config_file values to config FK.

    For each Article with a config_file value, look up the NewsConfig
    with a matching key and set the config FK.
    """
    Article = apps.get_model("newsserver", "Article")
    NewsConfig = apps.get_model("newsserver", "NewsConfig")

    # Build a mapping of config keys to NewsConfig instances
    config_map = {nc.key: nc for nc in NewsConfig.objects.all()}

    # Track statistics
    updated = 0
    skipped = 0
    missing_configs = set()

    for article in Article.objects.filter(config__isnull=True).iterator():
        if article.config_file:
            # Remove .yaml extension if present
            config_key = article.config_file
            if config_key.endswith(".yaml"):
                config_key = config_key[:-5]
            if config_key.endswith(".yml"):
                config_key = config_key[:-4]

            if config_key in config_map:
                article.config = config_map[config_key]
                article.save(update_fields=["config"])
                updated += 1
            else:
                missing_configs.add(config_key)
                skipped += 1
        else:
            skipped += 1

    if missing_configs:
        print(
            f"\nWarning: {len(missing_configs)} config keys not found: "
            f"{sorted(missing_configs)}"
        )
    print(f"\nMigrated {updated} articles, skipped {skipped}")


def reverse_migrate_config_fk_to_config_file(apps, schema_editor):
    """Reverse migration: populate config_file from config FK."""
    Article = apps.get_model("newsserver", "Article")

    for article in Article.objects.filter(config__isnull=False).iterator():
        if article.config:
            article.config_file = article.config.key
            article.save(update_fields=["config_file"])


class Migration(migrations.Migration):

    dependencies = [
        ("newsserver", "0012_newsconfig_country_newsconfig_database_url_and_more"),
    ]

    operations = [
        # Step 1: Add the config ForeignKey field (nullable initially)
        migrations.AddField(
            model_name="article",
            name="config",
            field=models.ForeignKey(
                blank=True,
                help_text="News configuration this article belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="newsserver.newsconfig",
            ),
        ),
        # Step 2: Make config_file nullable
        migrations.AlterField(
            model_name="article",
            name="config_file",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="DEPRECATED: Configuration file name (use config FK instead)",
                max_length=100,
                null=True,
            ),
        ),
        # Step 3: Remove old constraint (must be done before removing index)
        migrations.RemoveConstraint(
            model_name="article",
            name="unique_url_per_config",
        ),
        # Step 4: Remove old index on config_file + scraped_date
        migrations.RemoveIndex(
            model_name="article",
            name="newsserver__config__65c3c0_idx",
        ),
        # Step 5: Add new index on config + scraped_date
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["config", "scraped_date"],
                name="newsserver__config__ff4f6b_idx",
            ),
        ),
        # Step 6: Migrate data from config_file to config FK
        migrations.RunPython(
            migrate_config_file_to_config_fk,
            reverse_migrate_config_fk_to_config_file,
        ),
        # Step 7: Add new unique constraint on url + config
        # Note: This is added after data migration to avoid constraint violations
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                fields=["url", "config"],
                name="unique_url_per_config_fk",
            ),
        ),
    ]
