# Generated by Django 6.0 on 2026-01-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0013_add_article_config_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsconfig',
            name='email_enabled',
        ),
        migrations.AlterField(
            model_name='article',
            name='config_file',
            field=models.CharField(blank=True, db_index=True, default='', help_text='DEPRECATED: Configuration file name (use config FK)', max_length=100),
            preserve_default=False,
        ),
    ]
