# Generated by Django 6.0 on 2026-01-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0014_remove_newsconfig_email_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Topic name (e.g., 'Artificial Intelligence')", max_length=200, unique=True)),
                ('keywords', models.TextField(blank=True, help_text="Comma-separated keywords for fast matching (e.g., 'AI, machine learning, GPT, LLM')")),
                ('description', models.TextField(blank=True, help_text="Description of the topic for semantic matching (e.g., 'Articles about artificial intelligence, machine learning, and neural networks')")),
                ('similarity_threshold', models.FloatField(default=0.6, help_text='Minimum cosine similarity score (0-1) for semantic matching. Higher values = stricter matching.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Topics',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='newsconfig',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Topics to filter articles by. If empty, all articles are kept.', related_name='configs', to='newsserver.topic'),
        ),
    ]
