# Generated by Django 6.0 on 2026-02-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0024_fix_account_emailaddress_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberrequest',
            name='admin_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the immediate admin notification email was sent.', null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
