# Generated by Django 6.0.4 on 2026-05-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0028_alter_newsconfig_llm_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsconfig',
            name='logging_format',
        ),
        migrations.RemoveField(
            model_name='newsconfig',
            name='logging_level',
        ),
    ]
