# Generated by Django 6.0.5 on 2026-05-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0030_newsconfig_hero_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsconfig',
            name='hero_color_middle',
            field=models.CharField(blank=True, default='', help_text='Optional middle color for email hero gradient (hex, e.g. #7060da). Leave blank for a two-stop gradient.', max_length=7),
        ),
    ]
