# Generated by Django 6.0.5 on 2026-05-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0031_newsconfig_hero_color_middle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsconfig',
            name='llm_judge_model',
            field=models.CharField(default='gemini-2.0-flash', help_text='Model identifier for the judge LLM', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsconfig',
            name='llm_model',
            field=models.CharField(default='gemini-2.5-flash', help_text='LLM model identifier', max_length=200),
        ),
    ]
