# Generated by Django 6.0.5 on 2026-05-24 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsserver', '0032_alter_newsconfig_llm_judge_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Suggested name for the config (e.g., 'Austrian Tech News')", max_length=200)),
                ('sources', models.TextField(help_text='One source URL or name per line')),
                ('note', models.TextField(blank=True, help_text='Optional notes or context for this suggestion')),
                ('email', models.EmailField(help_text='Email of the submitter (denormalized)', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Config suggestion',
                'verbose_name_plural': 'Config suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
