"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from email.utils import formataddr
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

from newsbot.constants import TIMEZONE_STR

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent
REPORTS_DIR = BASE_DIR / "reports"
CONFIGS_DIR = BASE_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-g4#2kxrw1i2ric^oqhase(&szedhsy^te4dfvp_iom=p$4t6)k",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "true").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    *os.getenv("DJANGO_ALLOWED_HOSTS", "").split(","),
]
CSRF_TRUSTED_ORIGINS = [
    "https://" + host
    for host in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if host
]

# Behind a reverse proxy (e.g. Cloud Run): trust X-Forwarded-Proto so
# Django and django-allauth use https for redirect_uri and other
# absolute URLs.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition
SITE_ID = 1

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "web.newsserver",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "web.web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [Path(__file__).resolve().parent / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "web.newsserver.context_processors.has_logs",
            ],
        },
    },
]

WSGI_APPLICATION = "web.web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///webserver.sqlite3",
        conn_max_age=600,
        conn_health_checks=True,
    ),
}

# Supabase requires SSL
if DATABASES["default"].get("ENGINE") == "django.db.backends.postgresql":
    DATABASES["default"].setdefault("OPTIONS", {})["sslmode"] = "require"

    # Disable persistent connections when using a connection pooler.
    # Poolers (like Supabase) handle pooling themselves, so Django's
    # persistent connections cause stale connection issues.
    database_url = os.getenv("DATABASE_URL", "")
    if "pooler" in database_url.lower():
        DATABASES["default"]["CONN_MAX_AGE"] = 0


# Cache (in-memory). Used for magic-link rate limiting (see
# newsserver.auth_helpers for window and limits).
# LocMemCache is process-local; with multiple gunicorn workers each has
# its own cache. For single-process dev or one worker this is
# sufficient.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "newsbot-default",
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation"
            ".UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation.MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation.CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation.NumericPasswordValidator"
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = TIMEZONE_STR

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# App will be hosted under <ip>/newsbot/
FORCE_SCRIPT_NAME = os.getenv("FORCE_SCRIPT_NAME", "")
STATIC_URL = f"{FORCE_SCRIPT_NAME}/static/"
STATIC_ROOT = os.getenv("STATIC_ROOT", BASE_DIR / "staticfiles")

# WhiteNoise configuration for serving static files in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Auth: Subscriber is the user model; login only via Google
AUTH_USER_MODEL = "newsserver.Subscriber"
AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Allauth: use app login (Google) instead of admin for protected pages
LOGIN_URL = f"{FORCE_SCRIPT_NAME}/accounts/login/"
LOGIN_REDIRECT_URL = f"{FORCE_SCRIPT_NAME}/"
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGOUT_REDIRECT_URL = f"{FORCE_SCRIPT_NAME}/accounts/login/"

# Allauth: Subscriber uses email as USERNAME_FIELD, not username
ACCOUNT_USER_MODEL_USERNAME_FIELD = "email"
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "optional"
# New users from Google get a SubscriberRequest, not a Subscriber;
# redirected to subscription-requested page (see SocialAccountAdapter).
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_EMAIL_VERIFICATION = "optional"
SOCIALACCOUNT_ADAPTER = "web.newsserver.adapters.SocialAccountAdapter"
SOCIALACCOUNT_LOGIN_ON_GET = True

# Google OAuth (client id/secret from env).
# In Google Cloud Console → Credentials → OAuth 2.0 Client → add to
# "Authorized redirect URIs" the exact callback URL your app uses, e.g.:
#   http://localhost:8000/accounts/google/login/callback/
#   http://127.0.0.1:8000/accounts/google/login/callback/
# (Include trailing slash. If using FORCE_SCRIPT_NAME, include it, e.g.
#   http://localhost:8000/newsbot/accounts/google/login/callback/ )
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_OAUTH_CLIENT_ID", ""),
            "secret": os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", ""),
        },
        "SCOPE": ["profile", "email"],
    },
}

# Email (SMTP) for admin notifications (e.g. subscriber request digest)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_SMTP_SERVER", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_SMTP_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_SSL", "false").lower() not in (
    "true",
    "1",
    "yes",
)
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() in (
    "true",
    "1",
    "yes",
)
EMAIL_HOST_USER = os.getenv("EMAIL_SENDER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD", "")
# Sender format like report emails: "Display Name <email>"
_email_sender = os.getenv("EMAIL_SENDER", "")
_email_sender_name = os.getenv("EMAIL_SENDER_NAME", "The NewsBot")
DEFAULT_FROM_EMAIL = (
    formataddr((_email_sender_name, _email_sender)) if _email_sender else ""
)
# Recipient for daily subscriber-request digest
EMAIL_ADMIN_NOTIFICATION_TO = os.getenv("EMAIL_SENDER", "")
