name: 'Setup Python'
description: 'Sets up Python and installs uv using .python-version file'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
